# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5y4XIgdMHCKZmIc_MiHKiMaum-d-ryK
"""

from app import app

if __name__ == "__main__":
    app.run(debug=True)